
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameForm(object):
    def setupUi(self, GameForm):
        GameForm.setObjectName("GameForm")
        GameForm.resize(900, 700)
        GameForm.setMinimumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        GameForm.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GameForm)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsFrame = QtWidgets.QFrame(GameForm)
        self.settingsFrame.setMinimumSize(QtCore.QSize(220, 500))
        self.settingsFrame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.settingsFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.sizesCombo = QtWidgets.QComboBox(self.settingsFrame)
        self.sizesCombo.setObjectName("sizesCombo")
        self.verticalLayout.addWidget(self.sizesCombo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.isComputer = QtWidgets.QCheckBox(self.settingsFrame)
        self.isComputer.setObjectName("isComputer")
        self.verticalLayout.addWidget(self.isComputer)
        self.label = QtWidgets.QLabel(self.settingsFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.computerPlayerCombo = QtWidgets.QComboBox(self.settingsFrame)
        self.computerPlayerCombo.setObjectName("computerPlayerCombo")
        self.verticalLayout.addWidget(self.computerPlayerCombo)
        self.label_4 = QtWidgets.QLabel(self.settingsFrame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.difficultyLevelsCombo = QtWidgets.QComboBox(self.settingsFrame)
        self.difficultyLevelsCombo.setObjectName("difficultyLevelsCombo")
        self.verticalLayout.addWidget(self.difficultyLevelsCombo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.settingsFrame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.rulesText = QtWidgets.QTextBrowser(self.settingsFrame)
        self.rulesText.setObjectName("rulesText")
        self.verticalLayout.addWidget(self.rulesText)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(self.settingsFrame)
        self.startButton.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon)
        self.startButton.setIconSize(QtCore.QSize(20, 20))
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.horizontalLayout.addWidget(self.settingsFrame)
        self.boardFrame = QtWidgets.QFrame(GameForm)
        self.boardFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.boardFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.boardFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.boardFrame.setObjectName("boardFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.boardFrame)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.boardField = QtWidgets.QGridLayout()
        self.boardField.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.boardField.setObjectName("boardField")
        self.gridLayout_2.addLayout(self.boardField, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.boardFrame)

        self.retranslateUi(GameForm)
        QtCore.QMetaObject.connectSlotsByName(GameForm)

    def retranslateUi(self, GameForm):
        _translate = QtCore.QCoreApplication.translate
        GameForm.setWindowTitle(_translate("GameForm", "Form"))
        self.label_3.setText(_translate("GameForm", "Размер поля"))
        self.isComputer.setText(_translate("GameForm", "Игра с компьютером"))
        self.label.setText(_translate("GameForm", "Сторона компьютера"))
        self.label_4.setText(_translate("GameForm", "Сложность"))
        self.label_2.setText(_translate("GameForm", "Правила"))
        self.startButton.setText(_translate("GameForm", "Новая игра"))
import resources_rc
